version: '3.8'

services:
  api:
    container_name: api-elastic-beanstalk
    hostname: api-elastic-beanstalk
    build: ./
    command: npm run start:debug
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
      - "3001:3001"
    # env_file: "./docker/environments"